version: "3.9"
services:
  prometheus:
    image: prom/prometheus:v2.36.2
    container_name: prometheus
    networks:
      - back-tier
    restart: unless-stopped
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    # links:
    #   - cadvisor:cadvisor
    #   - alertmanager:alertmanager
    #      - pushgateway:pushgateway
    # depends_on:
    #   - cadvisor
    #      - pushgateway

  blackbox:
    container_name: blackbox
    networks:
      - back-tier
    restart: unless-stopped
    ports: [ '9115:9115' ]
    privileged: true
    image: prom/blackbox-exporter
    volumes:
      - './blackbox/blackbox.yml:/config/blackbox.yml'
    command:
      - '--config.file=/config/blackbox.yml'

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    networks:
      - back-tier
    restart: unless-stopped
    ports:
      - 9100:9100

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/etc/grafana/provisioning/
      - grafana_data:/var/lib/grafana
    networks:
      - back-tier
      - front-tier
    restart: unless-stopped
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD}
      GF_AUTH_ANONYMOUS_ENABLED: "true"

  # cadvisor:
  #   image: google/cadvisor:latest
  #   container_name: monitoring_cadvisor
  #   restart: unless-stopped
  #   volumes:
  #     - /:/rootfs:ro
  #     - /var/run:/var/run:rw
  #     - /sys:/sys:ro
  #     - /var/lib/docker/:/var/lib/docker:ro
  #   networks:
  #     - back-tier
  #   ports:
  #     - 8080:8080

networks:
  front-tier:
  back-tier:
volumes:
  prometheus_data: {}
  grafana_data: {}
